(function () {
  "use strict";

  const contacts = [
    {
      id: "chief",
      name: "김법률",
      role: "법률지원",
      tag: "법률지원 AI",
      group: "business",
      favorite: true,
      status: "away",
      color: "#ffe28a",
      avatar: "assets/avatar-thumbs/lawai.webp",
      greeting: "법률 쟁점을 주시면 로컬 자료에서 확인되는 근거와 확인 필요 사항을 나누어 정리하겠습니다.",
    },
    {
      id: "admin-officer",
      name: "김행정",
      role: "회계계약서무",
      tag: "행정실무 AI",
      group: "business",
      favorite: true,
      status: "away",
      color: "#dceac8",
      avatar: "assets/avatar-thumbs/hangjeongai.webp",
      greeting: "회계·계약·여비·서무 업무를 로컬 법령 근거와 행정실무 자료 범위에서 같이 살펴볼게요.",
    },
    {
      id: "language",
      name: "김언심",
      role: "언어지원 · 국어사전",
      tag: "언어지원 AI",
      group: "business",
      favorite: true,
      status: "offline",
      color: "#d8f3dc",
      avatar: "assets/avatar-thumbs/languageai.webp",
      greeting: "다듬을 문장을 보내 주세요. 원래 사실은 그대로 두고 자연스러운 업무 문장으로 정리할게요.",
    },
    {
      id: "translator",
      name: "김국어",
      role: "외국어 번역",
      tag: "외국어 AI",
      group: "business",
      favorite: true,
      status: "offline",
      color: "#cfe7ff",
      avatar: "assets/avatar-thumbs/langai.webp",
      greeting: "번역할 원문을 보내 주세요. 기존 번역본과 용어집이 있는지부터 확인하는 흐름으로 보여드릴게요.",
    },
    {
      id: "steno-officer",
      name: "김속기",
      role: "녹음속기",
      tag: "녹음속기 AI",
      group: "business",
      favorite: false,
      status: "offline",
      color: "#d7e8f7",
      avatar: "assets/avatar-thumbs/sokgiai.webp",
      tool: "steno",
      greeting: "오른쪽 받아쓰기 패널에서 녹음 또는 음성 파일 처리 흐름을 모의로 체험할 수 있어요.",
    },
    {
      id: "privacy-officer",
      name: "김개보",
      role: "개인정보검사",
      tag: "개인정보검사 AI",
      group: "business",
      favorite: false,
      status: "online",
      color: "#e5efd8",
      avatar: "assets/avatar-thumbs/gaeboai.webp",
      tool: "privacy",
      greeting: "오른쪽 검사실에서 합성 예시 창과 문장을 불러와 개인정보 후보 탐지 흐름을 체험해 보세요.",
    },
    {
      id: "image-officer",
      name: "김그림",
      role: "이미지생성",
      tag: "이미지생성 AI",
      group: "business",
      favorite: false,
      status: "offline",
      color: "#f4d2a1",
      avatar: "assets/avatar-thumbs/geurimai.webp",
      tool: "image",
      greeting: "오른쪽에서 용도와 비율을 고르면 생성 전 프롬프트 브리프를 모의로 만들 수 있어요.",
    },
    {
      id: "nori",
      name: "김노리",
      role: "수다지원",
      tag: "수다 AI",
      group: "business",
      favorite: false,
      status: "away",
      color: "#ffd7e8",
      avatar: "assets/avatar-thumbs/noriai.webp",
      greeting: "그냥 편하게 말 걸어도 돼. 할 일이면 누구한테 넘기면 좋을지도 같이 골라보자.",
    },
    {
      id: "file-converter",
      name: "김병환",
      role: "파일변환ㆍPDF편집",
      tag: "변환병합 AI",
      group: "technical",
      favorite: true,
      status: "online",
      color: "#dcebd5",
      avatar: "assets/avatar-thumbs/byeonghwanai.webp",
      tool: "converter",
      greeting: "오른쪽 변환 패널에서 샘플 파일을 넣고 병합·나누기 흐름을 직접 눌러볼 수 있습니다.",
    },
    {
      id: "resource-officer",
      name: "김자원",
      role: "문서자원추출",
      tag: "문서자원추출 AI",
      group: "technical",
      favorite: false,
      status: "online",
      color: "#e3dcf4",
      avatar: "assets/avatar-thumbs/jawonai.webp",
      tool: "resource",
      greeting: "오른쪽 문서 자원 패널에서 샘플 PPTX 분석과 이미지 선택 저장 흐름을 체험해 보세요.",
    },
    {
      id: "routine-officer",
      name: "김루틴",
      role: "자동화설계",
      tag: "자동화설계 AI",
      group: "technical",
      favorite: false,
      status: "online",
      color: "#d8f1dc",
      avatar: "assets/avatar-thumbs/routineai.webp",
      tool: "routine",
      greeting: "오른쪽 설정 패널에서 반복 횟수와 승인 지점을 둔 샘플 루틴을 모의 실행해 보세요.",
    },
  ];

  const scenarios = [
    {
      id: "law-alias",
      group: "법률·행정",
      officer: "김법률",
      role: "법률지원",
      avatar: "assets/avatar-thumbs/lawai.webp",
      title: "‘근기법’으로 연차수당 찾기",
      question: "직원이 연차수당을 못 받았대. ‘근기법’ 기준으로 뭘 확인해야 해?",
      reply:
        "검색어를 ‘근로기준법 + 연차유급휴가 + 미사용수당’으로 정리했습니다.\n\n먼저 확인할 자료\n• 입사일과 근속기간\n• 연차 발생·사용 일수\n• 사용촉진 실시 여부\n• 퇴직일과 수당 지급내역\n\n설치본은 ‘근기법’을 정식 법령명 후보로 바꾼 뒤 로컬 법령 자료에서 조문과 시행일을 확인합니다. ‘노동법’처럼 범위가 넓은 말은 연차·해고·퇴직금처럼 쟁점을 먼저 좁힙니다.",
      status: "웹 데모 · 실제 법령 검색 없음",
      cardTitle: "검토 메모 초안",
      cardItems: ["근기법 → 근로기준법 검색 후보", "연차 발생·사용·촉진 자료 확인", "확인된 조문·시행일만 근거로 표시"],
    },
    {
      id: "law-practice-term",
      group: "법률·행정",
      officer: "김법률",
      role: "법률지원",
      avatar: "assets/avatar-thumbs/lawai.webp",
      title: "소취·공소취소, 같은 말이야?",
      question: "회의록에 ‘소취’와 ‘공소취소’가 같이 나오는데 같은 말이야? 검토 메모로 정리해줘.",
      reply:
        "둘을 같은 말로 처리하면 안 됩니다.\n\n• 소취: 로컬 실무용어 자료에서 ‘소 취하’ 후보로 연결\n• 공소취소: 공식 용어 목록에서 별도 표제로 구분할 검색어\n\n설치본은 ‘후보 표현’과 ‘확인된 공식 표제’를 나눠 표시하고, 원문 문장과 사건 유형을 받아 각각 다른 법령·판례 검색어로 이어갑니다. 용어 구분만으로 사건의 효력까지 단정하지는 않습니다.",
      status: "웹 데모 · 실제 판례·사건 검토 없음",
      cardTitle: "용어 구분 결과",
      cardItems: ["소취 · 소 취하 후보", "공소취소 · 별도 공식 표제", "원문 문맥별 검색어를 각각 생성"],
    },
    {
      id: "admin-travel",
      group: "법률·행정",
      officer: "김행정",
      role: "회계계약서무",
      avatar: "assets/avatar-thumbs/hangjeongai.webp",
      title: "출장비 보완서류 정리",
      question: "자가용 출장인데 통행료 영수증을 잃어버렸고 카드 승인내역만 있어. 정산 전에 뭘 챙겨야 해?",
      reply:
        "정산 보완 체크리스트부터 만들었습니다.\n\n□ 출장명령서와 출장 결과 자료\n□ 이동 구간·일시·출장 목적\n□ 카드 승인내역\n□ 자가용 사용 사유와 사전 승인 여부\n□ 소속 기관의 여비 지침\n\n카드 승인내역만으로 대체 증빙이 되는지는 기관마다 다릅니다. 설치본은 로컬 규정을 대조해 ‘정산 가능 / 보완 후 가능 / 확인 필요’로 나누고, 담당자에게 확인할 항목까지 정리합니다.",
      status: "웹 데모 · 실제 여비 규정 조회 없음",
      cardTitle: "정산 전 준비물",
      cardItems: ["출장명령·목적·이동 구간", "카드 내역과 자가용 사용 사유", "기관별 대체 증빙 인정 기준"],
    },
    {
      id: "admin-purchase",
      group: "법률·행정",
      officer: "김행정",
      role: "회계계약서무",
      avatar: "assets/avatar-thumbs/hangjeongai.webp",
      title: "쪼개 사기 감사 체크",
      question: "같은 사업에 쓸 노트북과 모니터를 이번 달에 각각 300만원씩 따로 사도 돼? 감사 대비 체크리스트로 줘.",
      reply:
        "1차 판단: 품목명이 다르다는 이유만으로 바로 나누기보다, 하나의 수요인지부터 확인하는 편이 안전합니다.\n\n감사 대비 체크\n□ 같은 사업·예산·사용 목적·필요 시기인지\n□ 한 번에 발주할 수 있었는지\n□ 전체 수요 기준으로 예정가격을 산정했는지\n□ 따로 구매해야 하는 객관적 사유가 있는지\n□ 분리 사유와 견적·결재 과정이 문서에 남았는지\n\n설치본은 기관 구분 후 로컬 계약 근거에서 가능한 계약방식과 필요 서류를 확인합니다.",
      status: "웹 데모 · 실제 구매 승인·금액 판단 없음",
      cardTitle: "분리 구매 검토표",
      cardItems: ["사업·예산·목적·필요 시기의 동일성", "전체 수요와 예정가격 산정 과정", "분리 사유·견적·결재 기록"],
    },
    {
      id: "translate-sentence",
      group: "문서·언어",
      officer: "김국어",
      role: "외국어 번역",
      avatar: "assets/avatar-thumbs/langai.webp",
      title: "서비스 중단 공지 번역",
      question: "Due to scheduled maintenance, the online permit application service will be unavailable from 10:00 p.m. on August 20 to 6:00 a.m. on August 21. Applications submitted before the outage will not be affected.",
      reply:
        "번역 초안\n\n정기 점검으로 인해 8월 20일 오후 10시부터 8월 21일 오전 6시까지 온라인 인허가 신청 서비스를 이용할 수 없습니다. 서비스 중단 전에 제출된 신청 건에는 영향이 없습니다.\n\n확인할 용어\n‘permit application’은 실제 서비스 명칭에 따라 ‘허가 신청’, ‘인허가 신청’, ‘민원 신청’ 중 기관 용어집의 표현으로 통일해야 합니다.",
      status: "웹 데모 · 기존 번역본·기관 용어집 조회 없음",
      cardTitle: "번역 검토 포인트",
      cardItems: ["중단 시작·종료 시각 보존", "제출 완료 건의 처리 의미 보존", "서비스 공식 명칭 확인"],
    },
    {
      id: "rewrite-official",
      group: "문서·언어",
      officer: "김언심",
      role: "언어지원 · 국어사전",
      avatar: "assets/avatar-thumbs/languageai.webp",
      title: "민원 지연 보고 문장 정리",
      question: "7월 민원 128건 중 34건이 답변기한을 넘겼고, 담당자가 바뀌면서 인계가 제대로 안 돼서 그랬음. 다음 달부터 체크리스트 돌릴 예정.",
      reply:
        "다듬은 문안\n\n7월 접수 민원 128건 중 34건이 답변기한을 초과하였음. 담당자 변경 과정에서 업무 인계가 충분히 이루어지지 않은 것이 원인으로 파악됨. 재발 방지를 위해 다음 달부터 인계 체크리스트를 운영할 예정임.\n\n수치는 그대로 유지하고, 구어체를 현황 → 원인 → 개선 조치 순으로 정리했습니다. ‘다음 달’은 최종 보고서에서 실제 월로 바꾸면 더 분명합니다.",
      status: "웹 데모 · 입력 문장 밖의 사실 추가 없음",
      cardTitle: "보고 문장 정리 결과",
      cardItems: ["128건·34건 등 원문 수치 유지", "현황·원인·개선 조치 순으로 배열", "모호한 시점 1곳 확인 표시"],
    },
    {
      id: "pdf-workflow",
      group: "문서·언어",
      officer: "김병환",
      role: "파일변환·PDF편집",
      avatar: "assets/avatar-thumbs/byeonghwanai.webp",
      title: "PDF 3개 합치고 4~6쪽만",
      question: "표지·안건·붙임 PDF를 그 순서로 합친 다음, 통합본 4~6쪽만 ‘검토용’으로 따로 빼줘.",
      reply:
        "통합본 1개와 4~6쪽 검토본 1개로 정리할 수 있어요. 오른쪽 파일 슬롯을 표지 → 안건 → 붙임 순서로 맞춰 ‘PDF 병합’을 누르면 원본은 그대로 두고 통합본을 새 파일로 저장합니다.\n\n그 통합본을 슬롯에 다시 넣어 범위 ‘4-6’으로 나누면 검토용 PDF가 따로 만들어집니다. 암호화되거나 손상된 PDF는 처리 전에 오류로 알려줍니다.",
      status: "웹 데모 · 실제 PDF 열기·파일 생성 없음",
      cardTitle: "설치본 작업 결과",
      cardItems: ["표지 → 안건 → 붙임 순서로 통합", "통합본에서 4~6쪽만 별도 저장", "원본 PDF 3개는 그대로 유지"],
    },
    {
      id: "image-prompt",
      group: "창작·보안",
      officer: "김그림",
      role: "이미지생성",
      avatar: "assets/avatar-thumbs/geurimai.webp",
      title: "얼굴 없는 안내 프사 브리프",
      question: "민원 안내 담당 프사 하나 잡아줘. 사람 얼굴은 빼고, 작게 봐도 따뜻하고 믿음직하게.",
      reply:
        "브리프를 이렇게 잡았습니다.\n\n1:1 편집 삽화 · 열린 문과 작은 말풍선 · 아이보리 바탕 · 절제된 골드 포인트 · 작은 크기에서도 또렷한 구도\n\n생성 프롬프트\nMinimal warm public-service profile icon, an open door with a small speech bubble, ivory background, restrained golden accent, clean editorial illustration, centered composition, high contrast, no text\n\n제외: 사람 얼굴·실사 인물·기관 로고·글자·워터마크\n\n설치본에서는 오른쪽에서 문구를 고친 뒤 채팅의 ‘응, 생성해줘’로 확인해야 생성이 시작됩니다.",
      status: "웹 데모 · 프롬프트만 준비, 이미지 생성 없음",
      cardTitle: "프사 브리프",
      cardItems: ["1:1 · 편집 삽화 · 아이보리/골드", "열린 문 + 작은 말풍선", "얼굴·로고·글자·워터마크 제외"],
    },
    {
      id: "steno-meeting",
      group: "음성·자동화",
      officer: "김속기",
      role: "녹음속기",
      avatar: "assets/avatar-thumbs/sokgiai.webp",
      title: "회의 녹음에서 결정·할 일만",
      question: "회의 녹음본에서 결정사항과 할 일만 정리해줘. 담당자가 안 들리면 추측하지 마.",
      reply:
        "AI 정리 초안\n\n결정사항\n수정 보고서를 8월 20일까지 제출하기로 했습니다.\n\n할 일\n수정 보고서 제출 · 담당자 [확인 필요] · 기한 8월 20일\n\n설치본의 ‘녹음본 열기 + STT’로 받아쓰기 원문을 이 컴퓨터에서 만든 뒤, 현재 설정된 LLM으로 회의록 초안을 요청합니다. 고정 15분 제한은 없고 기본 120MB 보호 한도가 있으며, 화자분리는 제공하지 않습니다.",
      status: "웹 데모 · 고정 회의록 예시, 음성 파일 접근 없음",
      cardTitle: "샘플 회의록 요약",
      cardItems: ["결정 · 수정 보고서 8월 20일까지", "할 일 · 수정 보고서 제출", "담당자 · [확인 필요]"],
    },
    {
      id: "resource-pptx",
      group: "문서·언어",
      officer: "김자원",
      role: "문서자원추출",
      avatar: "assets/avatar-thumbs/jawonai.webp",
      title: "PPTX 속 원본 그림만 꺼내기",
      question: "이 사업계획서 PPTX에서 표지 이미지랑 조직도만 꺼내줘. 어디에 쓰였는지도 같이 보여줘.",
      reply:
        "샘플 분석 결과, 문서 자원 8개를 이미지 4개·글꼴 2개·테마 1개·구조 1개로 분류했습니다.\n\n표지 이미지와 조직도 PNG를 고르면 내부 경로와 확인 가능한 사용 위치를 함께 보고 각각 새 파일로 저장할 수 있어요. 원본 PPTX는 건드리지 않고 문서 내용도 채팅으로 보내지 않습니다. 매크로·스크립트는 발견만 표시하며 실행하지 않습니다.",
      status: "웹 데모 · 고정 분석 예시, 실제 문서 접근 없음",
      cardTitle: "찾아낸 문서 자원",
      cardItems: ["표지 이미지·조직도 PNG 선택", "내부 경로·확인 가능한 사용 위치 표시", "선택 저장 또는 전체 자원 ZIP"],
    },
    {
      id: "privacy-scan",
      group: "창작·보안",
      officer: "김개보",
      role: "개인정보검사",
      avatar: "assets/avatar-thumbs/gaeboai.webp",
      title: "발송 전 개인정보 2초 점검",
      question: "민원 답변 보내기 전에 개인정보가 남았는지 봐줘. 데모용 합성값은 010-0000-0000, demo@example.invalid야.",
      reply:
        "두 곳이 걸렸어요.\n\n휴대전화: 010-****-0000\n전자우편: de***@example.invalid\n\n원문은 손대지 않았고 마스킹 후보만 표시했습니다. 패턴 탐지 결과는 확정 판정이 아니므로 문맥을 한 번 확인해 주세요. 설치본도 사용자가 고른 창만 검사하며 자동 수정·저장·제출하지 않습니다.",
      status: "합성 데이터 데모 · 실제 창·클립보드 접근 없음",
      cardTitle: "발송 전 점검 결과",
      cardItems: ["휴대전화 후보 1건", "전자우편 후보 1건", "원문 수정·저장·제출 없음"],
    },
    {
      id: "routine-repeat",
      group: "음성·자동화",
      officer: "김루틴",
      role: "자동화설계",
      avatar: "assets/avatar-thumbs/routineai.webp",
      title: "30회 반복, 제출 앞에서 멈추기",
      question: "같은 값을 30번 입력하되 제출 버튼 앞에서는 내가 확인하게 해줘. 필요하면 무한 반복도 켜고 싶어.",
      reply:
        "설정안\n대상 칸 클릭 → 값 입력 → 제출 전 사용자 승인 → 다음 회차\n전체 반복 30회\n\n승인하기 전에는 제출 단계로 넘어가지 않도록 분리합니다. 무한 반복도 선택할 수 있지만 먼저 Ctrl+Shift+F12 긴급 중지를 확인해야 합니다.\n\n좌표형 자동화라 창 위치·해상도·배율·팝업 변화에 취약하고 업무 성공 여부까지 판단하지는 않습니다. 이 웹에서는 한 회차가 승인 지점에서 멈추는 장면만 보여줍니다.",
      status: "웹 데모 · OS 입력·자동화 실행 없음",
      cardTitle: "실행 전 안전장치",
      cardItems: ["전체 반복 30회 또는 무한 반복", "제출 전에 사용자 승인", "Ctrl+Shift+F12 긴급 중지"],
    },
    {
      id: "nori-overload",
      group: "대화",
      officer: "김노리",
      role: "수다지원",
      avatar: "assets/avatar-thumbs/noriai.webp",
      title: "머리 멈췄을 때 10분 정리",
      question: "오전엔 계약 검토, 오후엔 민원 보고인데 메일도 쌓였어. 머리가 멈춘 느낌이야.",
      reply:
        "그럴 때 우선순위를 더 고민하면 더 멈춰. 10분만 이렇게 하자.\n\n1. 계약 검토에 필요한 자료 세 개만 열기\n2. 민원 보고에서 빠진 확인사항을 한 줄로 적기\n3. 메일은 ‘오늘’과 ‘이번 주’ 두 칸으로만 나누기\n\n첫 25분은 계약 검토만 하자. 법령 쟁점은 김법률, 계약 절차와 증빙은 김행정에게 물을 수 있도록 질문 한 줄로 바꿔줄게.",
      status: "웹 데모 · 일정·메시지 생성·전송 없음",
      cardTitle: "지금 할 세 가지",
      cardItems: ["계약 검토 자료 세 개 열기", "민원 보고 확인사항 한 줄 적기", "메일을 오늘·이번 주로만 분류"],
    },
  ];

  const contactByName = new Map(contacts.map((contact) => [contact.name, contact]));
  scenarios.forEach((scenario) => {
    scenario.contactId = contactByName.get(scenario.officer)?.id || "";
  });

  window.HEYU_DEMO_CONTACTS = contacts;
  window.HEYU_DEMO_SCENARIOS = scenarios;
})();
